
steps:
  - checkout: self
    displayName: Checkout
    fetchDepth: '0'
    
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '6.x'
      installationPath: $(Agent.ToolsDirectory)/dotnet
    displayName: Install dotnet 6.x